package dev.reprotrail.ui.theme

import androidx.compose.ui.graphics.Color

private const val HEX_PRIMARY_GREEN = 0xFF2F6F5E
private const val HEX_PRIMARY_GREEN_LIGHT = 0xFF8ED8BD
private const val HEX_PRIMARY_CONTAINER_LIGHT = 0xFFD9F1E7
private const val HEX_PRIMARY_CONTAINER_DARK = 0xFF164C3C

private const val HEX_SECONDARY_GREEN = 0xFF6B7F75
private const val HEX_SECONDARY_GREEN_LIGHT = 0xFFB6CDC2
private const val HEX_SECONDARY_CONTAINER_LIGHT = 0xFFE7F2EC
private const val HEX_SECONDARY_CONTAINER_DARK = 0xFF2A3A34

private const val HEX_BACKGROUND_LIGHT = 0xFFF7FAF7
private const val HEX_BACKGROUND_DARK = 0xFF0F1513

private const val HEX_SURFACE_LIGHT = 0xFFFFFFFF
private const val HEX_SURFACE_DARK = 0xFF171F1C

private const val HEX_SURFACE_VARIANT_LIGHT = 0xFFEAF0EC
private const val HEX_SURFACE_VARIANT_DARK = 0xFF22302B

private const val HEX_TEXT_PRIMARY_LIGHT = 0xFF17201C
private const val HEX_TEXT_PRIMARY_DARK = 0xFFE7F1EC

private const val HEX_TEXT_SECONDARY_LIGHT = 0xFF5F6B64
private const val HEX_TEXT_SECONDARY_DARK = 0xFFB8C9C0

private const val HEX_OUTLINE_LIGHT = 0xFFD7E0DA
private const val HEX_OUTLINE_DARK = 0xFF394941

private const val HEX_ON_PRIMARY_DARK = 0xFF073326
private const val HEX_ON_SECONDARY_DARK = 0xFF10201A

private const val HEX_ON_PRIMARY_CONTAINER_LIGHT = 0xFF0E2A22
private const val HEX_ON_SECONDARY_CONTAINER_LIGHT = 0xFF1A2B24

private const val HEX_SUCCESS_GREEN = 0xFF3DAA75
private const val HEX_WARNING_YELLOW = 0xFFF4C95D
private const val HEX_ERROR_RED = 0xFFE5484D
private const val HEX_WHITE = 0xFFFFFFFF

internal val PRIMARY_GREEN = Color(HEX_PRIMARY_GREEN)
internal val PRIMARY_GREEN_LIGHT = Color(HEX_PRIMARY_GREEN_LIGHT)
internal val PRIMARY_CONTAINER_LIGHT = Color(HEX_PRIMARY_CONTAINER_LIGHT)
internal val PRIMARY_CONTAINER_DARK = Color(HEX_PRIMARY_CONTAINER_DARK)

internal val SECONDARY_GREEN = Color(HEX_SECONDARY_GREEN)
internal val SECONDARY_GREEN_LIGHT = Color(HEX_SECONDARY_GREEN_LIGHT)
internal val SECONDARY_CONTAINER_LIGHT = Color(HEX_SECONDARY_CONTAINER_LIGHT)
internal val SECONDARY_CONTAINER_DARK = Color(HEX_SECONDARY_CONTAINER_DARK)

internal val BACKGROUND_LIGHT = Color(HEX_BACKGROUND_LIGHT)
internal val BACKGROUND_DARK = Color(HEX_BACKGROUND_DARK)

internal val SURFACE_LIGHT = Color(HEX_SURFACE_LIGHT)
internal val SURFACE_DARK = Color(HEX_SURFACE_DARK)

internal val SURFACE_VARIANT_LIGHT = Color(HEX_SURFACE_VARIANT_LIGHT)
internal val SURFACE_VARIANT_DARK = Color(HEX_SURFACE_VARIANT_DARK)

internal val TEXT_PRIMARY_LIGHT = Color(HEX_TEXT_PRIMARY_LIGHT)
internal val TEXT_PRIMARY_DARK = Color(HEX_TEXT_PRIMARY_DARK)

internal val TEXT_SECONDARY_LIGHT = Color(HEX_TEXT_SECONDARY_LIGHT)
internal val TEXT_SECONDARY_DARK = Color(HEX_TEXT_SECONDARY_DARK)

internal val OUTLINE_LIGHT = Color(HEX_OUTLINE_LIGHT)
internal val OUTLINE_DARK = Color(HEX_OUTLINE_DARK)

internal val ON_PRIMARY_DARK = Color(HEX_ON_PRIMARY_DARK)
internal val ON_SECONDARY_DARK = Color(HEX_ON_SECONDARY_DARK)

internal val ON_PRIMARY_CONTAINER_LIGHT = Color(HEX_ON_PRIMARY_CONTAINER_LIGHT)
internal val ON_SECONDARY_CONTAINER_LIGHT = Color(HEX_ON_SECONDARY_CONTAINER_LIGHT)

internal val SUCCESS_GREEN = Color(HEX_SUCCESS_GREEN)
internal val WARNING_YELLOW = Color(HEX_WARNING_YELLOW)
internal val ERROR_RED = Color(HEX_ERROR_RED)
internal val WHITE = Color(HEX_WHITE)
